-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 02, 2018 at 08:06 PM
-- Server version: 8.0.12
-- PHP Version: 5.6.38

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ogms`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_schoolcourse`
--

CREATE TABLE `tbl_schoolcourse` (
  `SchoolCourseID` int(11) NOT NULL,
  `Subject` varchar(4) DEFAULT NULL,
  `Course` varchar(5) DEFAULT NULL,
  `CourseName` varchar(255) DEFAULT NULL,
  `Credit` varchar(50) DEFAULT NULL,
  `Prerequisites` varchar(255) DEFAULT NULL,
  `Description` varchar(1024) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_schoolcourse`
--

INSERT INTO `tbl_schoolcourse` (`SchoolCourseID`, `Subject`, `Course`, `CourseName`, `Credit`, `Prerequisites`, `Description`) VALUES
(6, 'CSC', '2302', 'Computer Programming II for Non-Majors', '5.0', 'CSC 2301 with a grade of \"C\" or better', 'This course is the second of a two-course sequence that introduces advanced computer programming. Topics include Object-Oriented Programming, Recursion, Graphical User Interface (GUI) development, database development, and the Internet and distributed computing.'),
(7, 'CSC', '2320', 'Fundamentals of Website Development', '3.0', 'familiarity with basic programming language concepts', 'This course provides a foundation for developing dynamic websites and web applications. The first part covers the front-end aspects of web development: creating, designing, and publishing content using HTML, CSS, and JavaScript. The second covers the back-end aspects: using programming languages to generate, manipulate, and manage content (CGI, cookies, server-side scripting), and accessing a database using SQL for common website tasks (forms, user registration). While this course covers web development concepts that are applicable to most popular platforms, it is significantly hands-on. A major component is a final project involving implementing a dynamic website.'),
(9, 'CSC', '2510', 'Theoretical Foundations of Computer Science', '3.0', 'CSC 1301 and (MATH 1112 or MATH 1113 or MATH 2211) with grade C or higher', 'This course covers the basic theoretical foundations required to study various sub-disciplines in computer science. Topics include: propositional and predicate logic with applications to logic programming, database querying, and program verification; induction and its application in proving correctness and termination of programs; recurrence relations, combinatorics, and graph theory with applications to analysis of algorithms; sets, relations, and functions and their applications in databases, functional programming, and automata.'),
(11, 'CSC', '2920', 'Ethical and Social Issues in Computing', '3.0', '', ' This course is dedicated to the study of social, ethical, and legal effects of computing on society and its users. Ethical concepts, professional codes of ethics, and the influence of computing on individuals, organizations, and the global economy will be addressed. Students will utilize critical thinking and problem-solving skills to analyze and debate case studies on topics some of which include privacy; intellectual property; computer crimes; system failures and implications; and, the impact of technology on society.'),
(12, 'CSC', '3210', 'Computer Organization & Programming', '3.0', 'CSC 1302, and CSC 2510 or MATH 2420 with grades of \"C\" or higher', 'This course covers the basic theoretical foundations required to study various sub-disciplines in computer science. Topics include: propositional and predicate logic with applications to logic programming, database querying, and program verification; induction and its application in proving correctness and termination of programs; recurrence relations, combinatorics, and graph theory with applications to analysis of algorithms; sets, relations, and functions and their applications in databases, functional programming, and automata.'),
(13, 'CSC', '3320', 'System-Level Programming', '3.0', 'CSC 1302, and CSC 2510 or MATH 2420 with grades of \"C\" or higher', 'An introduction to programming at the level of the operating system. Topics include editors, system calls, programming tools, files, processes, interprocess communication, and shells.'),
(14, 'CSC', '3330', 'C++ Programming', '3.0', 'CSC 3320 with grade of C or higher', 'Continuation of fundamental principles of computer programming. Topics covered include searching, sorting, and merging. Emphasis on structure and clarity as well as correctness.'),
(15, 'CSC', '4110', 'Introduction to Embedded Systems Laboratory', '4.0', 'CSC 3320 with grade of C or higher', '(Same as PHYS 4110.) Four lecture hours per week. Topics are taken from review of basic logic functions; automatic systems; microprocessor- based systems and applications; embedded system software survey; microprocessor-based applications; digital communications; and embedded systems programming.'),
(17, 'CSC', '4120', 'Introduction to Robotics', '4.0', 'CSC 3320 and MATH 3030 with grades of C or higher', 'The course focuses on programming robots. We will use robotic kits for the hardware, and program them using state-of-the-art languages, such as NQC.'),
(18, 'CSC', '4210', 'Computer Architecture', '4.0', 'CSC 3210 with grade of C or higher', 'Logic design, combinatorial and sequential circuits, input-output devices, memory, processors, controllers, parallel architectures, bit-slicing, reduced instruction sets. '),
(19, 'CSC', '4220', 'Computer Networks', '4.0', 'CSC 3320 and MATH 3030 with grades of C or higher', 'Introduction to computer networks; details of layered network protocols with emphasis on functionality and analysis. Principles of relevant state-of-the-art network standards.'),
(20, 'CSC', '4221', 'Wireless Networks & Mobile Computing', '4.0', 'CSC 2720 and CSC 3320 with grades of ', 'Introduction to wireless communication networks and mobile computing. Topics include wireless communications technology; communication protocols in wireless networks; representative network types such as cellular wireless networks, wireless LANs, wireless ad-hoc networks and wireless sensor networks, and mobile communication systems.'),
(21, 'CSC', '4222', 'Introduction to Information Security', '4.0', 'CSC 2720 and CSC 3320 with grades of \"C\" or higher', 'This course provides an initial overview on the topic of Information Security. It covers the basics of encryption and decryption, program security including viruses and other malicious code, application security, security in operating systems, security in networks and distributed systems, different methods of administering security, and legal and ethical issues in computer security.'),
(22, 'CSC', '4225', 'Internetwork Programming', '4.0', 'CSC 4220 with grade of C or higher', 'This course provides students with an understanding of the Internet and details regarding the protocols used on the Internet. The students will also learn key components of network programming using the most widely-used application program interface, sockets. Topics to be covered include Internet Protocol (IP), Transport Layer Protocol-Transmission Control Protocol (TCP), Transport Layer Protocol-User Datagram Protocol (UDP), and Unix/Linux Network Programming.'),
(23, 'CSC', '4260', 'Digital Image Processing', '4.0', 'CSC 2720 with grade of \"C\" or higher', 'Fundamentals of image processing, including image digitization, description, enhancement, segmentation, image transforms, filtering, restoration, coding, and retrieval. Concepts are illustrated by laboratory sessions in which these techniques are applied to practical situations, including examples from industrial and biomedical image processing.'),
(24, 'CSC', '4270', 'Introduction to Digital Signal Processing', '4.0', 'CSC 4210 with grade of C or higher', 'This course covers the nature of information, signals, transforms, and applications. Topics include analog to digital and digital to analog conversion, data storage (such as the audio format MP3), data transforms, and filters. Applications include noise reduction, signal analysis, volume control (e.g., audio signals), and compression. We will be using computer programs to handle mathematical modeling and calculations.'),
(25, 'CSC', '4310', 'Parallel and Distributed Computing', '4.0', 'CSC 3210 and CSC 3320 with grades of C or higher', 'Introduction to various parallel and distributed computing paradigms, algorithms, architectures, programming environments, and tools. Hands-on programming on both shared-memory and message-passing parallel architectures.'),
(26, 'CSC', '4320', 'Operating Systems', '4.0', 'CSC 3320 with grade of C or higher', 'Introduction to operating systems concepts. Topics may include multiprogramming, resources allocation and management, and their implementation.'),
(27, 'CSC', '4330', 'Programming Language Concepts', '4.0', 'CSC 2720 and CSC 3210 with grades of \"C\" or higher', 'Fundamental programming language concepts, including syntax versus semantics, binding time, scopes, and storage management.'),
(28, 'CSC', '4340', 'Introduction to Compilers', '4.0', 'CSC 2720 and CSC 3210 with grades of \"C\" or higher', 'Survey of topics related to compiler design, including parsing, table processing, code generation, and optimization.'),
(29, 'CSC', '4350', 'Software Engineering - CTW', '4.0', 'CSC 2720 with grade of \"C\" or higher', 'Techniques used in large scale scientific or technical software development, including requirements analysis, specification, systems design, implementation, testing, validation, verification, and maintenance. Serves as the Critical Thinking Through Writing (CTW) course required of all computer science majors.'),
(30, 'CSC', '4360', 'Mobile Application Development', '4.0', 'CSC 2720 with a grade of C or higher', 'Crosslisted with CSC 6360. This course will cover the technologies, tools, frameworks, and languages that are most commonly used in developing mobile applications for multiple mobile platforms. Topics include mobile application design, user interfaces, mobile application demographic and platform delivery, mobile networking, hosting infrastructure, and mobile security. '),
(31, 'CSC', '4370', 'Web Programming', '4.0', 'CSC 3320 with grade of C or higher', 'The course introduces the student to programming techniques required to develop Web applications. Topics include HTML forms, JavaScript, Servlets and Java Server Pages, PHP and MySQL, Web access to Oracle databases, and XML.'),
(32, 'CSC', '4380', 'Windowing Systems Programming', '4.0', 'CSC 3320 with grade of C or higher', 'Development of application software within windowed environments. Concepts of programming including graphical user interfaces, event-driven architectures, and object- oriented language programming with an application programming interface.'),
(33, 'CSC', '4510', 'Automata', '4.0', 'CSC 2720 with grade of C or higher', 'Theory of computing devices and the languages they recognize.'),
(34, 'CSC', '4520', 'Design and Analysis of Algorithms', '4.0', 'CSC 2720 and MATH 3030 with grades of \"C\" or higher', 'Techniques for designing efficient algorithms; analysis of algorithms; lower bound arguments; algorithms for sorting, selection, graphs, and string matching.'),
(35, 'CSC', '4610', 'Numerical Analysis I', '3.0', 'MATH 2215 with grade of C or higher and the ability to program in a high-level language', '(Same as MATH 4610.) Nature of error; iteration; techniques for nonlinear systems; zeros of functions; interpolation; numerical differentiation; Newton-Cotes formulae for definite integrals; computer implementation of algorithms.'),
(36, 'CSC', '4620', 'Numerical Analysis II', '3.0', 'Either MATH 3030 or both MATH 2641 and MATH 2215 with grades of C or higher, and the ability to program in a high level language', '(Same as MATH 4620.) Gaussian Elimination for linear systems; least squares; Taylor, predictor-corrector, and Runge- Kutta methods for solving ordinary differential equations; boundary value problems; partial differential equations.'),
(37, 'CSC', '4630', 'Introduction to Matlab Programming', '4.0', 'MATH 3030 with a grade of C or higher', 'This course is designed to give science majors experience with the Matlab programming language. Matlab is used for scientific applications involving images, sound, and other signals. No previous programming experience is needed.'),
(38, 'CSC', '4650', 'Introduction to Bioinformatics', '4.0', 'CSC 2720, BIOL 1103K, [or BIOL 1103 and BIOL 1103L] and CHEM 1211K [or CHEM 1211 and CHEM 1211L] with grades of \"C\" or higher', 'The explosion in biological knowledge due to various genome projects and other high-throughput techniques has created entirely new fields and industries, and a need for trained computational biologists who are familiar with Biology, Statistics, and Computer Science. This course will introduce principles underlying current techniques in the analysis of different kinds of biological data. Topics include: sequence alignment, database searching, microarrays, structure analysis, and phylogenetic tree algorithms.'),
(39, 'CSC', '4710', 'Database Systems', '4.0', 'CS 2720 with grade of ', 'An introduction to the fundamental concepts and principles that underlie the relational model of data. Topics include formal query languages; SQL; query optimization; relational database design theory; physical database design, integrity, security, and concurrency control.'),
(40, 'CSC', '4720', 'Human-Computer Interaction', '4.0', 'CSC 3320 with grade of C or higher', 'Techniques and methodologies for development of user interfaces in software systems; topics include interaction styles, interaction devices, user documentation, and interface assessment. '),
(41, 'CSC', '4730', 'Data Visualization', '4.0', 'CSC 3320 with grade of C or higher; for all other majors, consent of instructor', 'Data visualization is about displaying data in visual forms such as charts, diagrams, or 3D models. This course is targeted towards students who are interested in using data visualization in their work as well as those who are interested in developing visualization systems. Topics include the theoretical basis (e. g. Gestalt theory, visual attention, visual complexity theories), visualization techniques (e. g. interactive maps, time series charts, scatterplot maps, trees, networks, graphs, etc.), and visualization tools (e. g. Google Chart Tools, Processing). Students will learn basic visualization principles, how to choose the right kind of display for specific purposes, and how to provide interactive features for the user interface.'),
(42, 'CSC', '4740', 'Data Mining', '4.0', 'CSC 2720 with grade of C or higher', 'Introduction to basic data mining techniques (such as association rules mining, cluster analysis, and classification methods) and their applications (such as Web data mining, biomedical data mining and security).'),
(43, 'CSC', '4750', 'Semantic Web', '4.0', 'CSC 2720 with a grade of C or higher', ' Crosslisted with CSC 6750. An in-depth overview of the Semantic Web and how it can be applied. Major topics include core technical components and language constructs for the Semantic Web, linked data concepts/projects and RDF triple stores, and real world Semantic Web applications.'),
(44, 'CSC', '4760', 'Big Data Programming', '4.0', 'CSC 2720 with grade of C or higher', 'Crosslisted with CSC 6760. This course will cover the technologies, tools, frameworks, and languages that are most commonly used in Big Data Programming. The focus will be on algorithms for analyzing and mining massive datasets, graphs, and social network data. Topics include the storage, management, processing, and analysis of massive datasets, as well as Big Data governance, security, and privacy issues. '),
(45, 'CSC', '4810', 'Artificial Intelligence', '4.0', 'CSC 2720 and CSC 3210 with grades of C or higher', 'An overview of techniques and methodologies in the field of artificial intelligence. Topics may include search strategies, problem-solving, natural language processing, logic and deduction, memory models, learning, expert systems, knowledge representation, and robotics.'),
(46, 'CSC', '4820', 'Interactive Computer Graphics', '4.0', ' CSC 3320 with grade of \"C\" or higher', 'This course covers interactive 3D computer graphics techniques such as geometry modeling, transformation, lighting, texture mapping, graphics processing unit, shader, and user interaction.'),
(47, 'CSC', '4821', 'Fundamentals of Game Design', '4.0', 'CSC 3320 with grade of C or higher', 'Covers major aspects of game design such as challenges, gameplay, actions, core mechanics, worlds, characters, game balancing, user interfaces, and game genres.'),
(48, 'CSC', '4840', 'Computer Graphics Imaging', '4.0', 'CSC 3320 with a grade of C or higher', '(Same as GRD 4840 and Film 4840.) Study the theories, techniques, and tools for creating 3D graphics content. Topics include 3D modeling, camera, lighting, materials, texture mapping, physics-based modeling, basic animation, and rendering techniques (such as tracing and radiosity). '),
(49, 'CSC', '4841', 'Computer Animation', '4.0', 'CSC 3320 with a grade of C or higher', 'The basics of three-dimensional computer animation including 3D modeling, lighting, texture mapping, keyframing, character animation, rigid and soft-body dynamics, particles, cloth, hair, fluid, etc. '),
(50, 'CSC', '4870', 'Honors Thesis: Research', '3.0', 'Good standing with the Honors College and consent of instructor', 'Readings or research preparatory to honors thesis or project. This course may include a Signature Experience component. '),
(51, 'CSC', '4880', 'Honors Thesis: Writing', '3.0', 'CSC 4870 with grade of C or higher, good standing with the Honors College and consent of instructor', 'Writing or production of honors thesis or project. This course may include a Signature Experience component.'),
(52, 'CSC', '4920', 'Senior Project I', '2.0', 'CSC 3320, CSC 4210, and CSC 4350 with grades of C or higher', 'Consent of instructor may override the prerequisites in special circumstances. This course is meant to be the first part of two senior project classes. Students who enroll in this class are expected to enroll in the second part the following semester. Students will work as a team on a project, including planning the project, assigning roles, creating a time-line, literature research, acquiring equipment, and hardware and/or software design.'),
(53, 'CSC', '4921', 'Senior Project Il', '2.0', 'CSC 4920 with grade of C or higher', 'CSC 4921 consists of finishing the project from CSC 4920, followed by testing, revision, improvements, and further documentation. At the end of the semester, the team will turn in a comprehensive report detailing the project, its progress, evaluation, results, interpretation of the results, and conclusions. This report may be twice the size of the previous semester’s report, since it will likely include much of the first report. Also, the team is expected to explain and demonstrate the project.'),
(54, 'CSC', '4940', 'Computer Science Internship', '1.0 - 4.0', '', 'This course will require students to document and present the project they worked on during their internship. Students are able to register for the course at most 2 times for a maximum total of 4 credit hours to count towards their degree (excluding Area G). This course may include a Signature Experience component.'),
(55, 'CSC', '4980', 'Topics in Computer Science', '4.0', 'Consent of Instructor', 'Selected topics in Computer Science will be covered. Topics include the latest advances in computing.'),
(56, 'CSC', '4982', 'Undergraduate Research in Computer Science Credit Hours 3.0', '3.0', 'at least 12 upper-division hours in computer science', 'Authorization required. Independent investigation of topics of common interest to student and instructor. This course may include a Signature Experience component.'),
(57, 'CSC', '4995', 'Directed Readings B.I.S.-CTW', '3.0 - 4.0', '', 'Directed Readings designed for Bachelor of Interdisciplinary Studies students. This course may satisfy the junior and/or senior-level Critical Thinking Through Writing requirements.'),
(58, 'CSC', '4998', 'Selected Topics', '1.0 - 4.0', 'Consent of Instructor', 'No more than six credit hours may be applied toward the major. May be repeated if topics are different.'),
(59, 'CSC', '6110', 'Introduction to Embedded Systems Laboratory', '4.0', 'CSC 3210 for CSc student or PHYS 3500 for Physics students or equivalent course work with consent of instructor', '(Same as PHYS 4110.) Four lecture hours per week. Topics taken from: review of basic logic functions; automatic systems; microprocessor- based systems and applications; embedded system software survey; microprocessor-based applications; digital communications; and embedded systems programming.'),
(60, 'CSC', '6120', 'Introduction to Robotics', '4.0', 'CSC 3320 and MATH 3030', 'The course focuses on programming robots. We will use robotic kits for the hardware, and program them using state-of-the-art languages, such as NQC.'),
(61, 'CSC', '6210', 'Computer Architecture', '4.0', 'CSC 3210', 'Logic design, combinatorial and sequential circuits, input-output devices, memory, processors, controllers, parallel architectures, bit-slicing, reduced instruction sets.'),
(62, 'CSC', '6220', 'Computer Networks', '4.0', 'CSC 3320 and MATH 3030', 'Introduction to computer networks; details of layered network protocols with emphasis on functionality and analysis. Principles of relevant state-of-the art network standards.'),
(63, 'CSC', '6221', 'Wireless Networks and Mobile Computing', '4.0', 'CSC 4220 with grade of C or higher, or equivalent', 'Introduction to wireless communication networks and mobile computing. Topics include: wireless communications technology; communication protocols in wireless networks; representative network types such as cellular wireless networks, wireless LANs, wireless ad hoc networks and wireless sensor networks, and mobile communication systems.'),
(64, 'CSC', '6222', 'Introduction to Information Security', '4.0', 'CSC 4220 or CSC 6220 with a grade of C or higher', 'This course provides an initial overview on the topic of Information Security. It covers the basics of encryption and decryption, program security including viruses and other malicious code, application security, security in operating systems, security in networks and distributed systems, different methods of administering security, and legal and ethical issues in computer security.'),
(65, 'CSC', '6225', 'Internetwork Programming', '4.0', 'CSC 4220', 'This course provides students with an understanding of the Internet and details regarding the protocols used in the Internet. The students will also learn key components of network programming using the most-widely used application program interface, sockets. Topics to be covered include: Internet Protocol (IP), Transport Layer Protocol- Transmission Control Protocol (TCP), Transport Layer Protocol-User Datagram Protocol (UDP), and Unix/Linux Network Programming.'),
(66, 'CSC', '6260', 'Digital Image Processing', '4.0', 'CSC 3410', 'Fundamentals of image processing, including image digitization, description, enhancement, segmentation, image transforms, filtering, restoration, coding, and retrieval. Concepts are illustrated by laboratory sessions in which these techniques are applied to practical situations, including examples from industrial and biomedical image processing.'),
(67, 'CSC', '6270', 'Introduction to Digital Signal Processing', '4.0', 'CSC 4210 or CSC 6210', 'This course covers the nature of information, signals, transforms, and applications. Topics include analog to digital and digital to analog conversion, data storage (such as the audio format MP3), data transforms, and filters. Applications include noise reduction, signal analysis, volume control (e.g., audio signals), and compression. We will be using computer programs to handle mathematical modeling and calculations.'),
(68, 'CSC', '6310', 'Parallel and Distributed Computing', '4.0', 'CSC 3210 and CSC 3320', 'Introduction to various parallel and distributed computing paradigms, algorithms, architectures, programming environments, and tools. Hands-on programming on both shared-memory and message-passing parallel architectures.'),
(69, 'CSC', '6320', 'Operating Systems', '4.0', 'CSC 3320', 'Introduction to operating systems concepts. Topics may include multiprogramming, resources allocation and management, and their implementation.'),
(70, 'CSC', '6330', 'Programming Language Concepts', '4.0', 'CSC 3210 and CSC 3410', 'Fundamental programming language concepts, including syntax versus semantics, binding time, scopes, and storage management.'),
(71, 'CSC', '6340', 'Introduction to Compilers', '4.0', 'CSC 4330 or CSC 6330', 'Survey of topics related to compiler design, including parsing, table processing, code generation, and optimization.'),
(72, 'CSC', '6350', 'Software Engineering', '4.0', 'CSC 3410', 'Techniques used in large scale scientific or technical software development, including requirements analysis, specification, systems design, implementation, testing, validation, verification, and maintenance.'),
(73, 'CSC', '6360', 'Mobile Application Development', '4.0', 'CSC 3410 with C or better grade', 'Cross-listed with CSC 4360. This course will cover the technologies, tools, frameworks and languages that are most commonly used in developing mobile applications for multiple mobile platforms. Topics include mobile application design, user interfaces, mobile application demographic and platform delivery, mobile networking, hosting infrastructure, and mobile security.'),
(74, 'CSC', '6370', 'Web Programming', '4.0', 'CSC 2310', 'The course introduces the student to programming techniques required to develop Web applications. Topics include: HTML forms, JavaScript, Servlets and Java Server pages, PHP and MySQL, Web access to Oracle databases, and XML.'),
(75, 'CSC', '6380', 'Windowing Systems Programming', '4.0', 'CSC 2310', 'Development of application software within windowed environments. Concepts of programming including graphical user interfaces, event-driven architectures, and object- oriented language programming with an application programming interface.'),
(76, 'CSC', '6510', 'Automata', '4.0', 'CSC 2510', 'Theory of computing devices and the languages they recognize.'),
(77, 'CSC', '6520', 'Design and Analysis of Algorithms', '4.0', 'CSC 3410 and MATH 3030', 'Techniques for designing efficient algorithms; analysis of algorithms; lower bound arguments; and algorithms for sorting, selection, graphs, and string matching.'),
(78, 'CSC', '6610', 'Numerical Analysis I', '3.0', 'MATH 2215 and the ability to program in a high-level language', 'Nature of error; iteration; techniques for nonlinear systems; zeros of functions; interpolation; numerical differentiation; Newton-Cotes formulae for definite integrals; and computer implementation of algorithms.'),
(79, 'CSC', '6620', 'Numerical Analysis II', '3.0', 'MATH 3030 or MATH 3435, and the ability to program in a high-level language', '(Same as MATH 6620.) Gaussian Elimination for linear systems; least squares; Taylor, predictor-corrector and Runge-Kutta methods for solving ordinary differential equations; boundary value problems and partial differential equations.'),
(80, 'CSC', '6630', 'Introduction to Matlab Programming', '4.0', '', 'This course is designed to give science majors experience with the Matlab programming language. Matlab is used for scientific applications involving images, sound, and other signals. No previous programming experience is needed.'),
(81, 'CSC', '6640', 'Fundamentals of Bioinformatics', '4.0', 'BIOL 3800 or written approval of instructor', '(Same as BIOL 6640 and CHEM 6640.) Four lecture hours per week. A â€œhands-onâ€ approach to bioinformatics using PCs, the internet, and computer graphics to analyze, correlate, and extract information from biological databases, emphasizing sequence and structure databases for protein and nucleic acids, and introducing the computing skills necessary for bioinformatics. Topics include: sequences and three-dimensional structures of proteins and nucleic acids, the major databases, algorithms for sequence comparison, data mining, and prediction of structure and function.'),
(82, 'CSC', '6650', 'Introduction to Bioinformatics', '4.0', 'CSC 3410, BIOL 1103K, and CHEM 1211K', 'The explosion in biological knowledge due to various genome projects and other high-throughput techniques has created entirely new fields and industries, and a need for trained computational biologists who are familiar with Biology, Statistics, and Computer Science. This course will introduce principles underlying current techniques in the analysis of different kinds of biological data. Topics include: sequence alignment, database searching, microarrays, structure analysis, and phylogenetic tree algorithms.'),
(83, 'CSC', '6720', 'Human-Computer Interaction', '4.0', 'CSC 2310', 'Techniques and methodologies for development of user interfaces in software systems; topics include interaction styles, interaction devices, user documentation, and interface assessment.'),
(84, 'CSC', '6730', 'Data Visualization', '4.0', 'for computer science majors, CSC 2310 with grade of C or higher, or equivalent; for all other majors, consent of instructor', 'Data visualization is about displaying data in visual forms such as charts, diagrams, or 3D models. This course is targeted towards students who are interested in using data visualization in their work as well as those who are interested in developing visualization systems. Topics include the theoretical basis (e.g. Gestalt theory, visual attention, visual complexity theories), visualization techniques (e.g. interactive maps, time series charts, scatterplot maps, trees, networks, graphs, etc.), and visualization tools (e.g. Google Chart Tools, Processing). Students will learn basic visualization principles, how to choose the right kind of display for specific purposes, and how to provide interactive features for the user interface.'),
(85, 'CSC', '6740', 'Data Mining', '4.0', 'CSC 3410', 'Introduction to basic data mining techniques (such as association rules mining, cluster analysis, and classification methods) and their applications (such as Web data mining, biomedical data mining and security).'),
(86, 'CSC', '6741', 'Data Mining for Analytics', '3.0', '', 'Introduction to data mining techniques for structured as well as unstructured data including text mining. Topics will include data cleaning and pre-processing, association rules mining, cluster analysis, and classification methods. The course will have numerous hands-on programming projects.'),
(87, 'CSC', '6750', 'Semantic Web', '4.0', 'CSC 3410 with a grade of C or better', 'Cross-listed with CSC 6750. In-depth overview of the Semantic Web and how it can be applied. Major topics include core technical components and language constructs for the Semantic Web, linked data concepts/projects and RDF triple stores, and real world semantic Web applications.'),
(88, 'CSC', '6760', 'Big Data Programming', '4.0', 'CSC 3410 with grade of C or better', 'Cross-listed with CSC 6760. This course will cover the technologies, tools, frameworks and languages that are most commonly used in Big Data Programming. Focus will be on algorithms for analyzing and mining massive datasets, graphs and social network data. Topics include the storage, management, processing and analysis of massive datasets, as well as Big Data governance, security, and privacy issues'),
(89, 'CSC', '6810', 'Artificial Intelligence', '4.0', 'CSC 3410 and CSC 4330 or CSC 6330', 'An overview of techniques and methodologies in the field of artificial intelligence. Topics may include search strategies, problem solving, natural language processing, logic and deduction, memory models, learning, expert systems, knowledge representation, and robotics.'),
(90, 'CSC', '6820', 'Interactive Computer Graphics', '4.0', 'CSC 2310', 'This course covers interactive 3D computer graphics techniques such as geometry modeling, transformation, lighting, texture mapping, graphics processing unit, shader, and user interaction.'),
(91, 'CSC', '6821', 'Fundamentals of Game Design', '4.0', 'CSC 2310', 'Covers major aspects of game design such as challenges, gameplay, actions, core mechanics, worlds, characters, game balancing, user interfaces, and game genres.'),
(92, 'CSC', '6840', 'Computer Graphics Imaging', '4.0', '', '(Same as COMM 6840.) Study the theories, techniques, and tools for creating 3D computer graphics content. Topics include 3D modeling, camera, lighting, materials, texture mapping, physics based modeling, basic animation, and rendering techniques (e.g. ray tracing and radiosity).'),
(93, 'CSC', '6841', 'Computer Animation', '4.0', '', 'The basics of three-dimensional computer animation including 3D modeling, lighting, texture mapping, key framing, character animation, rigid and soft body dynamics, particles, cloth, hair, fluid, etc.'),
(94, 'CSC', '6980', 'Topics in Computer Science', '4.0', 'Consent of Instructor', 'Selected topics in Computer Science will be covered. Topics include the latest advances in computing.'),
(95, 'CSC', '7350', 'Programming for Bioinformatics', '3.0', '', 'An introduction to a high-level programming language and basic data structures with a structured approach to problem solving, algorithmic analysis, and program development with emphasis on bioinformatics applications.'),
(96, 'CSC', '7351', 'Systems Programming for Bioinformatics', '3.0', '', 'Prerequisite CSC 7350. An introduction to programming at the level of the operating system. Topics include shell scripting and C programming with an emphasis on bioinformatics applications.'),
(97, 'CSC', '7352', 'Data Structures for Bioinformatics', '3.0', 'CSC 7351', 'Basic concepts and analysis of data representation and associated algorithms, including linearly-linked lists, multi-linked structures, trees, searching, and sorting with emphasis on bioinformatics applications. '),
(98, 'CSC', '8050', 'Statistics for Bioinformatics', '3.0', 'MATH 4544 or MATH 6544 or BIOL 4744 or BIOL 6744, or its equivalent', '(Same as BIOL 8050 and STAT 8050.) Three lecture hours per week. Introduction of computational biology and microarray informatics, gene expression analysis using microarray for transcriptional profiling, use of multivariate statistics and computer algorithms for different clustering techniques, important role of statistical packages, algorithms for calculating statistical quantities and statistical research in this area.'),
(99, 'CSC', '8210', 'Advanced Computer Architecture', '4.0', 'CSC 4210 or CSC 6210', 'Multiprocessors (including shared memory as well as distributed memory systems), vector processing, program and network properties, scalable performance, memory hierarchy (including cache memory organization), pipelining, and bus systems. Topical research papers will also be discussed.'),
(100, 'CSC', '8220', 'Advanced Computer Networks', '4.0', 'CSC 4220/6220, or consent of the instructor', 'Basics of queueing theory, network simulation, analysis methods, current network protocols, their implementation, potential extensions and improvements. Survey of current literature on performance analysis.'),
(101, 'CSC', '8221', 'Optical and Wireless Networks', '4.0', 'CSC 4220/6220', 'Topics may include various optical and wireless networks, enabling technologies, multiplexing techniques, WDM, broadcast networks, wavelength-routed networks, network architectures, protocols, personal communication service (PCS) networks, location management, network algorithms, and optimization problems.'),
(102, 'CSC', '8222', 'Network Security', '4.0', 'CSC 4220 or CSC 6220', 'This course provides students with a detailed understanding of the fundamentals of network security. Significant focus will be placed on the five phases of network attacks: reconnaissance, scanning, gaining access/denial of service, maintaining access, and covering tracks. Topics to be covered include: Web security, Security standards-SSL/TLS and SET, Intruders and viruses, PGP and S/MIME for electronic mail security, Firewalls, IDS Secret Key and Public/Private Key Cryptography Cryptographic Hashes and Message Digests, Authentication Systems (Kerberos), Digital signatures and certificates, Kerberos and X.509v3 digital certificates. Also, current network security publications will be surveyed.'),
(103, 'CSC', '8223', 'Wireless Sensor Networks', '4.0', 'CSC 4220 or CSC 6220', ' This course is intended to provide a general introduction to wireless sensor networks. The course will cover the fundamental concepts and principles; architectures; communication protocols such as MAC protocols, link layer protocols, naming and addressing, time synchronization, localization and positioning, topology control, and routing protocols; and data management in wireless sensor networks. Students will understand the basic knowledge of wireless sensor networks, be familiar with setting up a wireless network, gain experience of designing and implementing wireless sensor network protocols for different applications, and develop abilities of conducting research in wireless sensor networks.'),
(104, 'CSC', '8250', 'Advanced Netowrk Architectures and Protocols', '4.0', 'CSC 4220 or CSC 6220', 'This course covers the state-of-art network architectures, protocols, and algorithms. It starts with reviewing issues associated with the network design principles, protocol mechanisms, and implementation techniques. The challenges related to implementing efficient and reliable protocols are then discussed and illustrated through several representative techniques and algorithms such as MPLS and RSVP. In addition, the course introduces fault-management and traffic grooming technologies for emerging networks including dynamic optical, radio and overlay networks. Topics related to service classes and network convergences, as well as interactions among diverse networking paradigms are also covered.'),
(105, 'CSC', '8251', 'Sensor Web Architecture and Protocols', '4.0', 'CSC 4220/6220', ' This course surveys the emerging field of sensor web system and its applications. The course will cover a broad range of topics, including system architectures, operating systems, radio communication, networking protocols, energy management, RFID, web services and its applications (such as smart environments and smart grid). It is a research-oriented course that includes reading and discussion of papers from the scientific literature. Students will be expected to understand the algorithms and protocols in the lecture and read and present several selected research papers. The students will also gain hands-on experience with sensor web system and testbed and learn how to design practical sensor web systems.'),
(106, 'CSC', '8260', 'Advanced Image Processing', '4.0', 'CSC 4260/6260', 'Advanced research topics of image processing, which include image digitization, description, enhancement, segmentation, image transforms, filtering, restoration, coding, and retrieval.'),
(107, 'CSC', '8270', 'Digital Signal Processing', '4.0', 'CSC 4210/6210', 'The nature of information, signals, transforms, and applications. Topics include periodic sampling, the Fourier transform, finite impulse response filters, signal averaging, the Haar transform, and the wavelet transform.'),
(108, 'CSC', '8320', 'Advanced Operating Systems', '4.0', 'CSC 4320/6320', 'Advanced operating systems concepts and mechanisms. Topics may include process synchronization, process deadlock, distributed operating systems, atomicity, commitment, recovery, fault-tolerance, distributed leader election, distributed manual exclusion algorithm, and concurrency control.'),
(109, 'CSC', '8350', 'Advanced Software Engineering', '4.0', 'CSC 4350/6350', 'Advanced concepts in software engineering. Topics may include new life cycle paradigms, code reusability issues, formal specifications, new design methodologies, and others.'),
(110, 'CSC', '8370', 'Data Security', '4.0', 'CSC 4320/6320 or CSC 4210/6210 or CSC 4220/6220', 'The basics of data security and integrity in computer systems. The theoretical basis of data security, including concepts in cryptography, network protocols, operating systems, and authentication. Topics will include the structure, mechanism, and detection of computer viruses and worms; the use of firewalls and packet filters; common security lapses in operating systems and their prevention; checksums and basic cryptography; and related ideas such as buffer overflow attacks and indirect assembly programming. \"Real-world\" examples of attacks will be analyzed and discussed.'),
(111, 'CSC', '8520', 'Applied Combinatorics and Graph Theory', '3.0', 'CSC 4520/6520', 'Development of combinatorial and graphical algorithms. Techniques for the study of complexity with application to algorithms in graph theory, sorting, and searching.'),
(112, 'CSC', '8530', 'Parallel Algorithms', '4.0', 'CSC 6520', 'Techniques for designing and analyzing parallel algorithms on shared-memory and other models. Topics may include basic techniques, lists, trees, searching, sorting, graphs, and randomized algorithms.'),
(113, 'CSC', '8540', 'Advanced Algorithms in Bioinformatics', '4.0', 'CSC 4520 or CSC 6520 with grade of B or higher', 'This course is an advanced graduate level of the course CSC 4520/6520. It is focused on fundamental algorithmic techniques in bioinformatics, including classed methods such as dynamic programming, support vector machines and other statistical and learning optimization methods. Applications will include restriction mapping, gene prediction, DNA sequencing, phylogenetic trees, haplotype inference, disease association, DNA array analysis, gene networks.'),
(114, 'CSC', '8550', 'Advanced Algorithms with Applications to Networks', '4.0', 'CSC 4520/CSC 6520', 'Advanced data structures and algorithms. Liner Programming, Integer Linear Programming, approximation algorithms. Algorithms and protocols for sensor and ad hoc wireless networks. Protocols for improvement of communication networks survivability and reliability.'),
(115, 'CSC', '8560', 'Discrete Approximation Algorithms and Metaheuristics', '4.0', 'CSC 4520 or CSC 6520 with a grade of C or higher', 'Approximation algorithms and metaheuristics for combinatorial problems: Set Cover, Steiner Trees, Multiway Cut, k-Center, Feedback Vertex Set, Shortest Superstring, Knapsack, Bin Packing, Minimum Makespan Scheduling. Primal-Dual Approximation algorithms: Steiner Forest.'),
(116, 'CSC', '8610', 'Advanced Numerical Analysis', '3.0', 'MATH 4435/6435 and CSC 4610/6610', 'Advanced topics in numerical analysis. Stability and conditioning, discretization error, and convergence. Examples are drawn from linear algebra, differential and nonlinear equations.'),
(117, 'CSC', '8620', 'Numerical Linear Algebra', '3.0', 'MATH 4435/6435 and CSC 4610/6610', 'Computational aspects of linear algebra. Matrix factorization, least squares, orthogonal transformations, eigenvalues, and methods for sparse matrices.'),
(118, 'CSC', '8630', 'Advanced Bioinformatics', '4.0', 'CSC 6640 or equivalent, ability to program in Java or C++ or equivalent, and consent of instructor', ' (Same as BIOL 8630 and CHEM 8630.) Advanced topics in bioinformatics, computer and internet tools, and their applications. Computer skills for the analysis and extraction of functional information from biological databases for sequence and structure of nucleic acids and proteins. Students will complete a computer-based bioinformatics project.'),
(119, 'CSC', '8710', 'Deductive Databases and Logic Programming', '4.0', 'CSC 4710/6710', 'An introduction to the area of deductive databases and logic programming. Topics include syntax of logic programs and deductive databases, model-theoretic, proof-theoretic and fixed-point semantics, operational semantics such as bottom-up evaluation and SLD-resolution techniques, query optimization, negation, constraint checking, and applications of deductive databases.'),
(120, 'CSC', '8711', 'Databases and the Web', '4.0', 'CSC 4710/6710, or consent of instructor', 'Application of database technology to access information on the World Wide Web. Topics include Common Gateway Interface (CGI), HTML form processing, accessing databases from the Web, search engines, query languages for Web data, semi-structured data model, and XML.'),
(121, 'CSC', '8712', 'Advanced Database Systems', '4.0', 'CSC 6710', 'Advanced topics in database systems will be discussed: transaction processing, atomicity-consistency-isolation- durability (ACID) requirements of transactions, transaction processing in Internet, distributed databases, transaction models, concurrency control, middleware in transaction processing systems, application integration, semi- structured data, on-line analytical processing, data warehouses, real-time and active databases.'),
(122, 'CSC', '8713', 'Spatial and Scientific Databases', '4.0', 'CSC 6710', 'This course will cover a number of advanced concepts: spatial databases, high-dimensional data indexing (with applications in Content-based Image Retrieval through kNN querying), data warehouses, and an introduction to emerging spatio-temporal database systems. The lectures will provide graduate students with sufficient foundation to conduct their own, but supervised research in the field of databases at the graduate level. Students will gain hands on experience on the chosen aspect of database systems through completion of an individual graduate research project.'),
(123, 'CSC', '8720', 'Advanced Human-Computer Interaction', '4.0', 'CSC 4350/6350 and CSC 4720/6720', 'Current trends in user interface technology; topics include alternative interaction devices, user interface tools, and interface modeling techniques.'),
(124, 'CSC', '8740', 'Advanced Data Mining', '4.0', 'CSC 6710 and CSC 6740 with a B or better grade', 'Advanced concepts in data mining: sequence data analysis, time-series data classification and forecasting (with usage of dynamic time warping and kNN classifiers), high-dimensional data analysis (with applications to high-dimensional data indexing), and emerging area of spatio-temporal patterns discovery. The lectures will provide students with sufficient foundation to conduct their own, but supervised research on the challenges of mining unconventional data (e.g. image, time-series, or spatiotemporal data) from massive real-life data repositories.'),
(125, 'CSC', '8810', 'Computational Intelligence', '4.0', 'CSC 4810/6810', 'Introduction to computational intelligence techniques and their applications. Major topics include soft computing, granular computing, knowledge discovery and data mining, distributed intelligent agents, etc. How to implement an actual intelligent system is also covered.'),
(126, 'CSC', '8820', 'Advanced Graphics Algorithms', '4.0', 'CSC 4820/CSC 6820', 'Study advanced algorithms and tools for computer graphics programming; topics include 3D pipeline, graphics processing unit, shader programming, view, transformation, texture mapping, game programming, and 3D graphics for mobile devices.'),
(127, 'CSC', '8840', 'Modeling and Simulation Theory and Application', '4.0', 'programming maturity is assumed', ' The course covers theory and application of computer modeling and simulation. It includes basic systems modeling concepts and in-depth discussions of modeling elements, simulation protocols, and their relationships. In-class exposition of modeling and simulation techniques will be based on the discrete event modeling and simulation (DEVS) framework. Possible application domains of this class are numerous, including computer network, ecological systems, social/biological systems, and business to name a few.'),
(128, 'CSC', '8850', 'Machine Learning Prerequisite: CSC 4520/6520', '4.0', '', 'This course is intended to provide a general introduction to machine learning. This course will cover the fundamental concepts and principles of supervised learning and unsupervised learning, including concept learning, decision tree, artificial neural network, evaluating hypotheses, bayesian learning, instance-based learning, genetic algorithm, support vector machine, reinforcement learning, clustering algorithm, feature selection and feature extraction. Students will understand the basic knowledge of machine learning, be familiar with various supervised learning and unsupervised learning methods, gain experience of designing and implementing machine learning methods for dataset with different characteristics, and develop abilities of conducting research in machine learning. 4.000 Credit hours.'),
(129, 'CSC', '8900', 'Seminar in Computer Science', '1.0', '', 'Discussion of current research in computer science.'),
(130, 'CSC', '8901', 'Perspectives in Computer Science', '1.0', '', 'For the Course Only Option in the M.S. degree, this seminar course is required. This course covers the topics in central areas of computer science, recent developments and future directions. 1.000 Credit Hours.'),
(131, 'CSC', '8910', 'Computer Science Topics Seminar', '1.0-3.0', '', 'May be repeated if topic varies.'),
(132, 'CSC', '8920', 'Computer Science Teaching Pedagogy', '1.0', 'consent of instructor', 'The course covers pedagogical issues related to teaching computer science courses.'),
(133, 'CSC', '8930', 'M.S. Project', '1.0 - 4.0', 'consent of project advisor', 'This course will fulfill the project option in the M.S. degree.'),
(134, 'CSC', '8940', 'Computer Science Internship', '1.0-9.0', '', 'The course will require to document and present the project the student worked on during the internship.'),
(135, 'CSC', '8950', 'Directed Research in Computer Science', '1.0 - 4.0', 'consent of instructor', ''),
(136, 'CSC', '8980', 'GRAPH DATA MINING/MULTIMEDIA SYSTEMS/CRYPTOGRAPHY/DEEP LEARNING', '4.0', 'consent of instructor', 'May be taken more than once if topics are different.'),
(137, 'CSC', '8981', 'Research in Computer Science', '1.0-15.0', 'consent of instructor', ' May be repeated.'),
(138, 'CSC', '8982', 'Lab in Computer Science', '1.0-15.0', 'consent of instructor', ' May be repeated.'),
(139, 'CSC', '8999', 'Thesis Research', '1.0-9.0', 'consent of thesis advisor', ''),
(140, 'CSC', '9900', 'Seminar in Computer Science', '1.0', '', ' One lecture hour a week. Discussion of current research in computer science.'),
(141, 'CSC', '9999', 'Doctoral Dissertation Research', '1.0-20.0', '', '');
INSERT INTO `tbl_schoolcourse` (`SchoolCourseID`, `Subject`, `Course`, `CourseName`, `Credit`, `Prerequisites`, `Description`) VALUES
(142, 'CSC', '6710', 'Database Systems', '4.0', 'CSC 3410', 'An introduction to the fundamental concepts and principles that underlie the relational model of data. Topics include formal query languages; SQL; query optimization; relational database design theory; and physical database design, integrity, security, and concurrency control.'),
(143, 'CSC', '1010', '1010', '4', '11111', '111111111');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_schoolcourse`
--
ALTER TABLE `tbl_schoolcourse`
  ADD PRIMARY KEY (`SchoolCourseID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_schoolcourse`
--
ALTER TABLE `tbl_schoolcourse`
  MODIFY `SchoolCourseID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=149;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
